github.com:
    users:
        BaleyEccles:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: BaleyEccles
